server {
        listen 192.168.31.86:5378 ssl http3;
        server_name test2.genmeta.net;

        allow           all;
        deny            all;

        ssl_certificate /Users/x/code/genmeta/gateway_new/nginx/keychain/test2.genmeta.net/test2-genmeta-net-ECC.crt;
        ssl_certificate_key /Users/x/code/genmeta/gateway_new/nginx/keychain/test2.genmeta.net/test2-genmeta-net-ECC.key;

        location / {
            proxy_pass      http://192.168.31.86:6000;
        }
}
