server {
        listen 192.168.1.51:5378 ssl http3;
        server_name test2.genmeta.net;

        allow           all;
        deny            all;

        ssl_certificate /Users/lixiaofeng/code/gateway/keychain/test2.genmeta.net/test2-genmeta-net-ECC.crt;
        ssl_certificate_key /Users/lixiaofeng/code/gateway/keychain/test2.genmeta.net/test2-genmeta-net-ECC.key;

        location / {
            proxy_pass      http://192.168.1.51:6000;
        }
}
