server {
        listen 127.0.0.1:5379;
        server_name     test3.genmeta.net;

        location / {
            allow           all;
            deny            all;
            proxy_pass      https://test3.genmeta.net:6001;
        }
}