#!/bin/sh

set -e

case "$1" in
    remove|remove-in-favour|deconfigure|deconfigure-in-favour)
        if command -v systemctl > /dev/null 2>&1 && systemctl is-active --quiet pishoo; then
            systemctl stop pishoo
        elif [ -x "/etc/init.d/pishoo" ]; then
            invoke-rc.d pishoo stop || exit $?
        fi
        ;;
    upgrade|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0