pishoo {
    # TODO client 证书
    proxy {
        listen 127.0.0.1:5379;
        resolver 1.12.74.4:5300;

        # TODO 支持配置匹配域名进行转发
        allow *.genmeta.net;
        deny doc.genmeta.net api.genmeta.net;
    }
}