pishoo {
    proxy {
        listen 127.0.0.1:5379;

        # 客户端配置 (可选)
        client_name query.test.genmeta.net;
        ssl_certificate /Users/lixiaofeng/code/gmdns/examples/keychain/query.test.genmeta.net/query.test.genmeta.net-ECC.crt;
        ssl_certificate_key /Users/lixiaofeng/code/gmdns/examples/keychain/query.test.genmeta.net/query.test.genmeta.net-ECC.key;

        allow *.genmeta.net;
        deny doc.genmeta.net api.genmeta.net, daan.genmeta.net;
    }
}