pishoo {
    proxy {
        listen 127.0.0.1:5379;

        client_name usopp.pilot.genmeta.net;
        dns h3 https://localhost:4433;
        ssl_certificate /Users/lixiaofeng/Downloads/ssl/usopp.pilot.genmeta.net.test-ca/usopp.pilot.genmeta.net.pem;
        ssl_certificate_key /Users/lixiaofeng/Downloads/ssl/usopp.pilot.genmeta.net.test-ca/usopp.pilot.genmeta.net.key;

        allow *.genmeta.net;
    }
}