pishoo {
    proxy {
        listen 127.0.0.1:5379;

        # 客户端证书认证（可选）
        client_name borber.pilot.dhttp.net;
        ssl_certificate /Users/x/code/genmeta/gateway/gateway/keychain/borber.pilot.dhttp.net/borber.pilot.dhttp.net.pem;
        ssl_certificate_key /Users/x/code/genmeta/gateway/gateway/keychain/borber.pilot.dhttp.net/borber.pilot.dhttp.net.key;

        allow *.dhttp.net;
        deny doc.dhttp.net api.dhttp.net, daan.dhttp.net;
    }
}
