pishoo {
    include       mime.types;
    default_type  application/octet-stream;
    pid /root/pishoo-stun/pishoo.pid;
    access_rules sqlite:///root/pishoo-stun/rules.db?mode=rw;

    server {
        listen eth0 20002;
        server_name stun.genmeta.net;

        ssl_certificate /root/pishoo-stun/stun.genmeta.net/stun.genmeta.net.pem;
        ssl_certificate_key /root/pishoo-stun/stun.genmeta.net/stun.genmeta.net.key;

        stun_server {
            bind 10.1.12.7:20002;
            outer_addr 43.139.23.164:20002;
            change_addr 101.33.241.121:20003;
            change_port 20003;
        }

        stun_server {
            bind [2402:4e00:c011:1700:8624:7e0:5c9a:1]:20002;
            outer_addr [2402:4e00:c011:1700:8624:7e0:5c9a:1]:20002;
            change_addr [2402:4e00:c011:1700:8624:7e0:5c9a:0]:20003;
            change_port 20003;
        }
    }
}
