pishoo {
    pid /Users/lixiaofeng/code/gateway/pishoo-ocsp-local.pid;

    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen all 5378;
        server_name usopp.pilot.genmeta.net;
        dns h3 https://localhost:4433;

        ssl_certificate /Users/lixiaofeng/Downloads/ssl/usopp.pilot.genmeta.net.test-ca/usopp.pilot.genmeta.net.pem;
        ssl_certificate_key /Users/lixiaofeng/Downloads/ssl/usopp.pilot.genmeta.net.test-ca/usopp.pilot.genmeta.net.key;

        location / {
            root            /Users/lixiaofeng/code/gateway;
            index           README.md;
            add_header Cache-Control no-cache;
        }
    }
}