pishoo {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen all 5378;
        server_name ljsy.test.genmeta.net;

        ssl_certificate /Users/lixiaofeng/Downloads/ljsy.test.genmeta.net/ljsy.test.genmeta.net.pem;
        ssl_certificate_key /Users/lixiaofeng/Downloads/ljsy.test.genmeta.net/ljsy.test.genmeta.net.key;

        # location / {
        #     root            /Users/lixiaofeng/Downloads/flvdemo;
        #     index           index.html;
        # }

        # location /live {
        #     proxy_pass    http://127.0.0.1:8000/;
        # }

        location / {
            proxy_pass   http://localhost:3000;
            add_header Access-Control-Allow-Origin * always;
            

        }

        location /mcp_server {
            proxy_pass   http://localhost:8123;
            add_header Access-Control-Allow-Origin * always;
            proxy_set_header Host 127.0.0.1;
            proxy_set_header Connection "keep-alive";
        }

        location /v1 {
            proxy_pass   http://localhost:11434;
            add_header Access-Control-Allow-Origin * always;
        }

        location /ssh {
            ssh_login basic;
            ssh_deny root;
        }

    }

}