pishoo {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen all 5378;
        server_name borber.pilot~;

        ssl_certificate /Users/x/code/genmeta/gateway/gateway/keychain/borber.pilot.genmeta.net/borber.pilot.genmeta.net.pem;
        ssl_certificate_key /Users/x/code/genmeta/gateway/gateway/keychain/borber.pilot.genmeta.net/borber.pilot.genmeta.net.key;

        location / {
            root            /Users/x/code/genmeta/gateway/chatbot-ui;
            index           index.html;
        }

        location /api/ {
            proxy_pass    http://127.0.0.1:3000/;
            proxy_set_header X-UA $http_user_agent;
            proxy_set_header X-Test $arg_test_id;
            proxy_set_header X-Real-Ip $remote_addr;
        }

        location /ssh {
            ssh_login basic;
            ssh_deny root;
        }

    }

    server {
        listen all 5378;
        server_name api.borber.pilot~;

        ssl_certificate /Users/x/code/genmeta/gateway/gateway/keychain/borber.pilot.genmeta.net/borber.pilot.genmeta.net.pem;
        ssl_certificate_key /Users/x/code/genmeta/gateway/gateway/keychain/borber.pilot.genmeta.net/borber.pilot.genmeta.net.key;


        location / {
            root            /Users/x/code/genmeta/gateway/chatbot-ui;
            index           index.html;
        }

        location /ssh {
            ssh_login basic;
            ssh_deny root;
        }

    }
}