pishoo {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen en1 5378;
        server_name publish.test.genmeta.net;
        server_id 0;

        ssl_certificate /Users/lixiaofeng/code/gmdns/examples/keychain/publish.test.genmeta.net/publish.test.genmeta.net-ECC.crt;
        ssl_certificate_key /Users/lixiaofeng/code/gmdns/examples/keychain/publish.test.genmeta.net/publish.test.genmeta.net-ECC.key;
        
        location / {
            root            /Users/lixiaofeng/Downloads/flvdemo;
            index           index.html;
            add_header Access-Control-Allow-Origin * always;
            add_header Cache-Control no-cache;
        }

        location /live/livestream.flv {
            proxy_pass http://localhost:8080/live/livestream.flv;
            add_header Access-Control-Allow-Origin * always;
            add_header Cache-Control no-cache;
        }

        location /api {
            proxy_pass    http://127.0.0.1:3000/;
            proxy_set_header X-UA $http_user_agent;
            proxy_set_header X-Test $arg_test_id;
            proxy_set_header X-Real-Ip $remote_addr;
        }

        location /ssh {
            ssh_login basic;
            ssh_deny root;
        }

    }

}