pishoo {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 0.0.0.0:5378;
        # server_name test.genmeta.net;
        server_name api.test.genmeta.net;

        resolver udp 1.12.74.4:5300;

        # ssl_certificate /Users/x/code/genmeta/gateway/gateway/keychain/test.genmeta.net/test.genmeta.net.pem;
        # ssl_certificate_key /Users/x/code/genmeta/gateway/gateway/keychain/test.genmeta.net/test.genmeta.net.key;
        ssl_certificate /home/reimu/code/user.pem;
        ssl_certificate_key /home/reimu/code/user.key;

        location /ssh {
            ssh_login basic;
            ssh_deny root;
        }

    }
}