http3 {
    # TODO client 证书
    server {
        listen 192.168.31.86:5379;

        location / {
            resolver        8.8.8.8;
            proxy_pass      https://$http_host$request_uri;
        }
    }
}