http3 {
    server {
        listen 192.168.31.86:5378 ssl http3;
        server_name test1.genmeta.net;

        ssl_certificate /Users/x/code/genmeta/gateway_new/gateway/keychain/test1.genmeta.net/test1-genmeta-net-ECC.crt;
        ssl_certificate_key /Users/x/code/genmeta/gateway_new/gateway/keychain/test1.genmeta.net/test1-genmeta-net-ECC.key;

        #location / {
        #    proxy_pass      http://127.0.0.1:5999;
        #}

        location / {
            root            /Users/x/code/genmeta/gateway_new/chatbot-ui/;
        }
    }
}
