import { expect, test } from '@playwright/test'

test.describe.configure({ mode: 'serial' })
test.beforeEach(({}, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Mutating workflows run once')
})

test('review decisions update the pending queue', async ({ page }) => {
  await page.goto('./approvals')
  const firstRow = page.locator('tbody tr').filter({ has: page.getByRole('button', { name: 'Allow', exact: true }) }).first()
  await expect(firstRow).toBeVisible()
  await firstRow.getByRole('button', { name: 'Allow' }).click()
  await page.getByRole('dialog', { name: /Allow request/ })
    .getByRole('button', { name: 'Allow', exact: true }).click()
  await expect(page.getByText('Request allowed', { exact: true })).toBeVisible()
  const secondRow = page.locator('tbody tr').filter({ has: page.getByRole('button', { name: 'Allow', exact: true }) }).first()
  await expect(secondRow).toBeVisible()
  await secondRow.getByRole('button', { name: 'Deny' }).click()
  await page.getByRole('dialog', { name: /Deny request/ })
    .getByRole('button', { name: 'Deny', exact: true }).click()
  await expect(page.getByText('Request denied', { exact: true })).toBeVisible()
})

test('contact editing and status actions can be restored', async ({ page }) => {
  await page.goto('./contacts')
  await page.getByRole('button', { name: /Alice Chen/ }).click()
  const alias = page.getByLabel('Local alias')
  await alias.fill('Alice QA')
  await page.getByRole('button', { name: 'Save alias' }).click()
  await expect(page.getByText('Alias updated', { exact: true })).toBeVisible()
  await alias.fill('Alice Chen')
  await page.getByRole('button', { name: 'Save alias' }).click()
  await page.getByRole('button', { name: 'Close contact details' }).click()

  await page.getByRole('button', { name: /Build Bot/ }).click()
  await page.getByRole('button', { name: 'Restore' }).click()
  await expect(page.getByText('Contact restored', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Block' }).click()
  await expect(page.getByText('Contact blocked', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close contact details' }).click()

  await page.locator('.contact-link').filter({ hasText: 'carol.example' }).click()
  await page.getByRole('button', { name: 'Grant chat' }).click()
  await expect(page.getByText('Chat delivery granted', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close contact details' }).click()

  await page.locator('.contact-link').filter({ hasText: 'legacy-agent.example' }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  const deleteDialog = page.getByRole('dialog', { name: 'Delete contacts (1)' })
  await deleteDialog.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByText('1 contact deleted', { exact: true })).toBeVisible()
  await expect(page.locator('.contact-link').filter({ hasText: 'legacy-agent.example' })).toHaveCount(0)
})

test('access rules can be added, edited and deleted', async ({ page }) => {
  await page.goto('./settings/access')
  await page.getByRole('button', { name: 'Add rule', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Access rules', exact: true })
  await editor.getByLabel('API path', { exact: true }).fill('/workspace-qa/manual-rule')
  await editor.getByLabel('Grantee', { exact: true }).fill('**')
  await editor.getByLabel('Effect', { exact: true }).selectOption('allow')
  await editor.getByRole('button', { name: 'Save rule', exact: true }).click()
  await expect(editor).toHaveCount(0)

  const rule = page.locator('.rule-detail tbody tr').filter({ hasText: '**' })
  await expect(rule).toContainText('allow')
  await rule.getByRole('button', { name: 'Edit', exact: true }).click()
  await expect(editor.getByLabel('API path', { exact: true })).toBeDisabled()
  await expect(editor.getByLabel('Method', { exact: true })).toBeDisabled()
  await expect(editor.getByLabel('Grantee', { exact: true })).toBeDisabled()
  await editor.getByLabel('Effect', { exact: true }).selectOption('deny')
  await editor.getByRole('button', { name: 'Save rule', exact: true }).click()
  await expect(editor).toHaveCount(0)
  await expect(rule).toContainText('deny')

  await page.getByRole('tab', { name: 'By grantee', exact: true }).click()
  await page.locator('.master-list-items > button').filter({ hasText: '**' }).click()
  const byGrantee = page.locator('.rule-detail tbody tr').filter({ hasText: '/workspace-qa/manual-rule' })
  await expect(byGrantee).toContainText('deny')
  await byGrantee.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('dialog', { name: 'Delete access rule?' })
    .getByRole('button', { name: 'Delete rule', exact: true }).click()
  await expect(byGrantee).toHaveCount(0)
})
